print("Hello world!")
print()
print("I like Python")
print()
print("Python is free and open source.")
print()
print("Python is easy to understand.")
print()
print("Python is free and open source.\n")
print("Python is easy to understand.")
print()
print("Python is free and open source.","Python is just the language for you.","Python enables programs to be written compactly and readably.")
print()
print("Python is free and open source.",end=" ")
print("Python is easy to understand.")
print("Python is extensible.",end=" ")
print("Python is simple to use.")
print()
print("Some Python","modules","are also useful as scripts.",sep=" *")
print()
print()
print("By default","this code","ends with a newline..",sep="*",end="*\n")
